version: "3"

services:
    
    php:
        container_name: php
        build:
            context: ./php
        volumes:
            - ./../application/:/var/www/
        # networks:
        #     - internal
        #     - external
        
        
    nginx:
        container_name: nginx
        build:
            context: ./nginx
        restart: always
        ports:
            - 8080:80
        volumes:
            - ./../application/:/var/www
        depends_on:
            - php
        # networks:
        #     - external

# networks:
#   external:
#     driver: bridge
#   internal:
#     driver: bridge